# https://taskfile.dev

version: "3"

vars:
  RM1: '{{if eq .OS "Windows_NT"}}powershell -NoProfile -Command Remove-Item -Recurse -Force {{else}}rm -rf{{end}}'
  RM: '{{if eq .OS "Windows_NT"}}cmd /d /c rmdir /q /s{{else}}rm -rf{{end}}'
  PY: '{{if eq .OS "Windows_NT"}}py -3{{else}}python3{{end}}'
  PIP: '{{if eq .OS "Windows_NT"}}py -3 -m pip{{else}}pip3{{end}}'
  YARN: "yarn"

env:
  UnityPath: C:\Program Files\Unity\Hub\Editor\2022.3.7f1\Editor\Unity.exe

tasks:
  kill-python:
    cmds:
      - '{{if eq .OS "Windows_NT"}}powershell -NoProfile -Command Stop-Process -Name python -Force{{else}}pkill -f python{{end}}'

  remove-cache:
    deps: [kill-python]
    internal: true
    vars:
      TARGET: '{{default ".build" .TARGET}}'
    cmds:
      - '{{if eq .OS "Windows_NT"}}cmd /d /c if exist "{{.TARGET}}" rmdir /q /s "{{.TARGET}}"{{end}}'

  prepare-build:
    internal: true
    vars:
      TARGET: '{{default ".build" .TARGET}}'
    cmds:
      - '{{if eq .OS "Windows_NT"}}cmd /d /c if not exist "{{.USER_WORKING_DIR}}\.build" mkdir "{{.USER_WORKING_DIR}}\.build"{{end}}'

  unity-build:
    deps: [prepare-build]
    internal: true
    vars:
      PROJECT: '{{default "DartRoom" .PROJECT}}'
    cmds:
      - '{{if eq .OS "Windows_NT"}}cmd /d /c if not exist "{{.USER_WORKING_DIR}}\.build" mkdir "{{.USER_WORKING_DIR}}\.build"{{end}}'
      - dotnet UnityBuildRunner -quit -batchmode -buildTarget "Win64" -projectPath "{{.USER_WORKING_DIR}}/{{.PROJECT}}" -logfile "{{.USER_WORKING_DIR}}/.build/unity_build_{{.PROJECT}}.log"
    silent: false

  unity-build-dart-room:
    cmds:
      - task: unity-build
        vars: { PROJECT: "DartRoom" }

  unity-build-mesh-101:
    cmds:
      - task: unity-build
        vars: { PROJECT: "Mesh101" }

  unity-build-physics-effects-gallery:
    cmds:
      - task: unity-build
        vars: { PROJECT: "PhysicsEffectsGallery" }

  unity-build-science-building:
    cmds:
      - task: unity-build
        vars: { PROJECT: "ScienceBuilding" }

  unity-build-toybox:
    cmds:
      - task: unity-build
        vars: { PROJECT: "Toybox" }

  default:
    deps:
      [
        unity-build-dart-room,
        unity-build-mesh-101,
        unity-build-physics-effects-gallery,
        unity-build-science-building,
        unity-build-toybox,
      ]
